language: python

python:

  - "3.6"

install:

    pip install cython

script:

    pip install geatpy

    python -m geatpy --version

    pip uninstall geatpy -y

    python setup.py install

    python -m geatpy --version
